//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CSGOBetting
{
    using System;
    using System.Collections.Generic;
    
    public partial class bet
    {
        public long betid { get; set; }
        public long matchid { get; set; }
        public double amount { get; set; }
        public long teamid { get; set; }
        public string datetime { get; set; }
    
        public virtual match match { get; set; }
        public virtual team team { get; set; }
    }
}
