//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CSGOBetting
{
    using System;
    using System.Collections.Generic;
    
    public partial class match
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public match()
        {
            this.bets = new HashSet<bet>();
            this.odds = new HashSet<odd>();
        }
    
        public long matchid { get; set; }
        public long matchstatsid { get; set; }
        public long csgolid { get; set; }
        public long team1id { get; set; }
        public long team2id { get; set; }
        public long roster1id { get; set; }
        public long roster2id { get; set; }
        public long matchstatus { get; set; }
        public Nullable<long> winner { get; set; }
        public string datetime { get; set; }
        public Nullable<long> eventid { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<bet> bets { get; set; }
        public virtual @event @event { get; set; }
        public virtual team team { get; set; }
        public virtual team team1 { get; set; }
        public virtual matchstatu matchstatu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<odd> odds { get; set; }
    }
}
