//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CSGOBetting
{
    using System;
    using System.Collections.Generic;
    
    public partial class odd
    {
        public long matchid { get; set; }
        public double team1odds { get; set; }
        public double team2odds { get; set; }
        public long sourceid { get; set; }
    
        public virtual match match { get; set; }
        public virtual oddssource oddssource { get; set; }
    }
}
